name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Enable caching
      uses: actions/cache@v2
      with:
        path: '~/node_modules'
        key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build --if-present
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: '~/node_modules'
        key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install
    - name: Check lint
      run: npm run lint
    - name: Check style
      run: npm run stylelint
    - name: Check accessibility
      run: npm run pa11y-ci
